# Generated by Django 3.2.7 on 2021-10-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dislikes', models.ManyToManyField(related_name='dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
