# Generated by Django 3.2.7 on 2021-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
