# Generated by Django 3.2.7 on 2021-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborlyUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborlyuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborlyuser',
            name='posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
