# Generated by Django 3.2.7 on 2021-10-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborlyUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborlyuser',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborlyuser',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
