# Generated by Django 3.2.7 on 2021-10-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborlyUsers', '0002_auto_20211005_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborlyuser',
            name='homepage',
        ),
    ]
