# Generated by Django 3.2.7 on 2021-10-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('neighborlyUsers', '0003_remove_neighborlyuser_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborlyuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.neighborhood'),
        ),
    ]
